-- INSERT INTO apartments (name)
-- 	VALUES ('Eugene Field'), ('Nathaniel Hawthorne'), ('Mark Twain'), ('Louisa May Alcott'), ('Emily Dickinson'), ('Robert Frost');

-- INSERT INTO units (kind, apartment_id) VALUES
-- ('studio', 1), ('one_bedroom', 1),
-- ('studio', 1), ('one_bedroom', 1),
-- ('studio', 1), ('one_bedroom', 1),
-- ('studio', 1), ('one_bedroom', 1),
-- ('studio', 1), ('one_bedroom', 2),
-- ('studio', 2), ('one_bedroom', 2),
-- ('studio', 2), ('one_bedroom', 2),
-- ('studio', 2), ('one_bedroom', 2),
-- ('studio', 2), ('one_bedroom', 2),
-- ('studio', 2), ('one_bedroom', 2),
-- ('studio', 2), ('one_bedroom', 2),
-- ('studio', 3), ('one_bedroom', 3),
-- ('studio', 3), ('one_bedroom', 3),
-- ('studio', 3), ('one_bedroom', 3),
-- ('studio', 3), ('one_bedroom', 3),
-- ('studio', 3), ('one_bedroom', 3),
-- ('studio', 4), ('one_bedroom', 4),
-- ('studio', 4), ('one_bedroom', 4),
-- ('studio', 4), ('one_bedroom', 4),
-- ('studio', 4), ('one_bedroom', 4),
-- ('studio', 4), ('one_bedroom', 4),
-- ('studio', 4), ('one_bedroom', 5),
-- ('studio', 5), ('one_bedroom', 5),
-- ('studio', 5), ('one_bedroom', 5),
-- ('studio', 5), ('one_bedroom', 5),
-- ('studio', 5), ('one_bedroom', 5),
-- ('studio', 5), ('one_bedroom', 5),
-- ('studio', 5), ('one_bedroom', 5),
-- ('studio', 6), ('one_bedroom', 6),
-- ('studio', 6), ('one_bedroom', 6),
-- ('studio', 6), ('one_bedroom', 6),
-- ('studio', 6), ('one_bedroom', 6),
-- ('studio', 6), ('one_bedroom', 6),
-- ('studio', 6), ('one_bedroom', 6),
-- ('loft', 1), ('two_bedroom', 2),
-- ('loft', 1), ('two_bedroom', 2),
-- ('loft', 3), ('two_bedroom', 2),
-- ('loft', 3), ('two_bedroom', 3),
-- ('loft', 3), ('two_bedroom', 6),
-- ('loft', 3), ('two_bedroom', 1),
-- ('loft', 3), ('two_bedroom', 2),
-- ('loft', 1), ('two_bedroom', 1),
-- ('loft', 4), ('two_bedroom', 4),
-- ('loft', 4), ('two_bedroom', 4),
-- ('loft', 4), ('two_bedroom', 4),
-- ('loft', 4), ('two_bedroom', 4),
-- ('loft', 1), ('two_bedroom', 1),
-- ('loft', 6), ('two_bedroom', 1),
-- ('loft', 6), ('two_bedroom', 5),
-- ('loft', 1), ('two_bedroom', 5),
-- ('loft', 1), ('two_bedroom', 5),
-- ('loft', 5), ('two_bedroom', 4),
-- ('loft', 5), ('two_bedroom', 1),
-- ('loft', 5), ('two_bedroom', 1),
-- ('loft', 1), ('two_bedroom', 6),
-- ('loft', 1), ('two_bedroom', 6),
-- ('loft', 6), ('two_bedroom', 6),
-- ('loft', 1), ('two_bedroom', 1) ;


INSERT INTO tenants (name, unit_id) VALUES
('Ignatius Cummerata', 1),
('Ofelia Heidenreich', 2),
('Elsa Prohaska', 3),
('Vidal Connelly', 4),
('Melissa Flatley', 5),
('Jewel Schiller', 6),
('Cecilia Volkman', 7),
('Earl Lueilwitz', 8),
('Justice Dickinson', 9),
('Vance Lebsack', 10),
('Brendan McClure', 11),
('Carmen Bogisich', 12),
('Sabryna Cormier', 13),
('Paris Feil', 14),
('Jalon Kemmer', 15),
('Eudora Goyette', 16),
('Demarcus Luettgen', 17),
('Ryley Blick', 18),
('Alisa Crona', 19),
('Stephania Franecki', 20),
('Gregoria Hermiston', 21),
('Heather Rosenbaum', 22),
('Lesly Walsh', 23),
('Noelia Beier', 24),
('Felicia Mills', 25),
('Adrain Ziemann', 26),
('Burnice Torphy', 27),
('Mervin Frami', 28),
('Lorenza Spencer', 29),
('Ansley Gibson', 30),
('Finn Doyle', 31),
('Macey Kuphal', 32),
('Karina Cummings', 33),
('Melyssa Torp', 34),
('Margaretta Cummerata', 35),
('Wilson Moore', 36),
('Jaquan Reichert', 37),
('Justen Kshlerin', 38),
('Terrence Nikolaus', 39),
('Yazmin Langosh', 40),
('Vita Dare', 41),
('Selena Bednar', 42),
('Baylee Wilkinson', 43),
('Ayana Moore', 44),
('Frederic Effertz', 45),
('Crystal Daniel', 46),
('Jerrod Daniel', 47),
('Susie Roob', 48),
('Asia Nikolaus', 49),
('Edwina Stokes', 50),
('Angel Lockman', 51),
('Kendall Ritchie', 52),
('Jaren Crona', 53),
('Selina Dach', 54),
('Howard Breitenberg', 55),
('Kennith Yost', 56),
('Allison Kuphal', 57),
('Jamaal Corkery', 58),
('Fred Brakus', 59),
('Madisyn Murazik', 60),
('Gregorio D''Amore', 61),
('Emelia Mraz', 62),
('Saige Rippin', 63),
('Jacinto Heller', 64),
('Gertrude Prosacco', 65),
('Myron Dach', 66),
('Gayle Lowe', 67),
('Collin Bosco', 68),
('Rey Murazik', 69),
('Clotilde Green', 70),
('Otha Schuppe', 71),
('Isabell Collins', 72),
('Clara Hilpert', 73),
('Fannie Mosciski', 74),
('Lucio Koepp', 75),
('Raymundo Blick', 76),
('Herbert Schinner', 77),
('Mylene Armstrong', 78),
('Alden Hauck', 79),
('Jayda Keebler', 80),
('Kenna Romaguera', 81),
('Sarai Terry', 82),
('Abigayle Cummings', 83),
('Wendell Glover', 84),
('Lavinia Oberbrunner', 85),
('Henri Corwin', 86),
('Davin Rath', 87),
('Otilia Zboncak', 88),
('Kirstin White', 89),
('Mario West', 90),
('Adolphus Wiegand', 91),
('Nadia Roberts', 92),
('Ottis Kuhn', 93),
('Brycen Casper', 94),
('Terrance Schaden', 95),
('Larry Barton', 96),
('Wellington Volkman', 97),
('Annamae Corwin', 98),
('Rubie Halvorson', 99),
('Kacie Hand', 100),
('Talia Wiegand', 101),
('Marlee Prohaska', 102),
('Lulu Beier', 103),
('Walker Bosco', 104),
('Antonio Mueller', 105),
('Kathryn Morar', 106),
('Millie Muller', 107),
('Uriel Barrows', 108),
('Jaylin Hauck', 109),
('Nedra O''Keefe', 110),
('Rahsaan Mraz', 111),
('Dorthy Mohr', 112),
('Connie Ward', 113),
('Ubaldo Hegmann', 114),
('Bo Dickens', 115),
('Mohammad Lehner', 116);











